### ISSUE TITLE
Ganti menggunakan GatsbyJS

### ISSUE THREAD

**Issue by ramaID** [id-laravel/web-jigsaw#5]
Jadi, setelah aku tilik dari sudut pandang SEO, web ini belum SEO friendly. Trus, karena aku lagi coba-coba GatsbyJS juga, sepertinya asik kalau diimplementasikan kesini. Selain GatsbyJS SEO friendly, saat ini dia berkembang pesat sepertinya. Trus juga menjawab trends saat ini (dark mode, PWA, dll). Gimana?

**Comment by uyab** [comment]
Coba dipecah dulu masalahnya satu persatu. Terkait SEO, apa masalah(spesifik)nya ?

Dari awal, karena ini website tentang Laravel, maka dipilih teknologi yang based on laravel juga. Sepertinya lebih penting memperkaya konten (ganti design) dibanding ganti engine.

**Comment by uyab** [comment]
Melihat perkembangan JS belakangan ini yang sangat massive, sementara belum ada static site Laravel yg bisa mengimbangi, saya open lagi dengan ide ganti engine berbasis JS :)

**Comment by ramaID** [comment]
[remix.run](https://remix.run/) gimana, Pak @uyab?

**Comment by uyab** [comment]
Kalau https://astro.build/ sudah pernah nyicip?

**Comment by ramaID** [comment]
otw nyicip, Pak wkwk

pernah denger juga, sih
